### PR TITLE
Checks for modification in an effective way

### PR DESCRIPTION
**Pull request by JJ**
It was not really working, see #10 
also #6 while I was at it.

### CODE REVIEW

**Comment by JJ** [comment]
Please don't merge. This does not work as intended.

**Comment by JJ** [comment]
Ping?

**Comment by JJ** [comment]
Ping?

**Comment by finanalyst** [comment]
Seems OK

**Comment by JJ** [comment]
Er... you've closed it, not merged it...

**Comment by finanalyst** [comment]
closed without merging. Reopening, merging, closing

**Comment by JJ** [comment]
Maybe you'd want to release a new version now that includes these changes?

**Comment by JJ** [comment]
Ping? Will you release a new version?

**Pull request merged**
